services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: nubilus-galac
      POSTGRES_PASSWORD: glactice24v1
      POSTGRES_DB: nubilus
      # Optional: Enable TimescaleDB tuning
      TS_TELEMETRY: "off"
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

    # TODO: later add more services redis, frontend, backend

volumes:
  timescale_data:
    driver: local
